version: "3.9"

services:

  mysql:
    image: mysql:8.4
    container_name: mysql

    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: copilot_aralt_db
      MYSQL_USER: user
      MYSQL_PASSWORD: password

    ports:
      - "3306:3306"

    volumes:
      - mysql-data:/var/lib/mysql

  mailhog:
    image: mailhog/mailhog
    container_name: mailhog

    ports:
      - "1025:1025"
      - "8025:8025"

volumes:
  mysql-data: