spring.application.name=copilot-alart

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

spring.config.import=\
optional:file:./config/db.properties,\
optional:file:./config/mail.properties,\
optional:file:./config/server.properties