spring.application.name=copilot-alart

server.port=28080

spring.datasource.url=jdbc:sqlite:copilot_alart.db
spring.datasource.driver-class-name=org.sqlite.JDBC

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:create_table.sql
spring.sql.init.encoding=UTF-8

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# XXX javaメールの機能を追加
spring.mail.host=192.168.2.171
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false