spring.application.name=copilot-alart

server.port=28080

spring.datasource.url=jdbc:mysql://localhost:3306/copilot_aralt_db
spring.datasource.username=user
spring.datasource.password=password

spring.sql.init.mode=always
spring.sql.init.schema-locations=classpath:create_table.sql
spring.sql.init.encoding=UTF-8

mybatis.mapper-locations=classpath:mapper/*.xml
mybatis.configuration.map-underscore-to-camel-case=true

# XXX javaメールの機能を追加
spring.mail.host=127.0.0.1
spring.mail.port=1025
spring.mail.username=
spring.mail.password=
spring.mail.properties.mail.smtp.auth=false
spring.mail.properties.mail.smtp.starttls.enable=false